image: nkx1231/root6-geant4-garfield:0.4

stages:
  - build
  - loadRESTLibs
  - examples

before_script:
    - export USER="rest"

build:
  type: build
  script:
    - echo "**${CI_PROJECT_DIR}**"
    - rm -rf ${CI_PROJECT_DIR}/install
    - git clone --single-branch --branch development https://github.com/rest-for-physics/framework.git framework
    - cd framework
    - git submodule init source/libraries/geant4
    - git submodule update source/libraries/geant4
    - cd source/libraries/geant/
    - git checkout master
    - cd ../../../
    - git submodule init source/packages/restG4
    - git submodule update source/packages/restG4
    - cd source/packages/restG4/
    - git checkout master
    - cd ../../../
    - mkdir build
    - cd build
    - cmake ../ -DREST_WELCOME=ON -DREST_G4=ON -DINSTALL_PREFIX=${CI_PROJECT_DIR}/install
    - make install -j2
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install
      - ${CI_PROJECT_DIR}/framework
      - ${CI_PROJECT_DIR}/framework/build
    expire_in: 1 day

loadRESTLibs:
  type: loadRESTLibs
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - restRoot -b -q

#addSignalNoise: 
#  type: process
#  script:
#    - . ${CI_PROJECT_DIR}/install/thisREST.sh
#    - cd ${CI_PROJECT_DIR}/pipeline/processes/
#    - ./addNoise.py
