name: Validation

on:
  workflow_dispatch:

  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Release
  REST_PATH: /rest/framework/install

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lobis/root-geant4-garfield:rest-for-physics

    strategy:
      matrix:
        framework-branch: [master]

    steps:
      - name: Checkout REST Framework
        uses: actions/checkout@v3
        with:
          repository: rest-for-physics/framework
          ref: ${{ matrix.framework-branch }}
          path: /tmp/framework

      - name: Setup and install
        run: |
          cd /tmp/framework
          git submodule init source/libraries/geant4 && git submodule update source/libraries/geant4
          cd source/libraries/geant4/ && /tmp/framework/scripts/checkoutRemoteBranch.sh ${{ env.GITHUB_SHA }}
          cd /tmp/framework
          git submodule init source/packages/restG4 && git submodule update source/packages/restG4
          cd source/packages/restG4/ && git checkout ${{ env.GITHUB_SHA }}
          cd /tmp/framework
          mkdir -p build
          cd build
          cmake ../ -DREST_WELCOME=ON -DREST_G4=ON -DCMAKE_INSTALL_PREFIX=${{ env.REST_PATH }}
          make -j install
